[package]
name = "kubexp"
version = "0.1.0"
authors = ["hamadakafu <kafu.h1998@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "*"
termion = "*"
unicode-width = "*"
rand = "*"
anyhow = "*"
